### ISSUE TITLE
toString() / stringify() ?

### ISSUE THREAD

**Issue by stevenvachon** [baloneysandwiches/parse-srcset#11]
Would be useful

**Comment by albell** [comment]
Hi, thanks for the suggestion. The original goal here was very narrow, just to parse in a spec-conformant way, in the smallest possible footprint, for inclusion in client-side code like Picturefill. That's partly how Picturefill 3.0 was able get spec-conformance while still clocking in at just 12k or so.

This would be easy to add but it kind of represents a scope creep that I'm wary of. Please feel free to fork?

**Comment by stevenvachon** [comment]
Fair enough. Thank you.
